# Generated by Django 4.1.7 on 2023-03-09 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_rename_activate_category_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="price",
            new_name="slug",
        ),
    ]
